### ISSUE TITLE
ModuleNotFoundError: No module named 'tomllib'

### ISSUE THREAD

**Issue by dziewannak** [gaborschulz/ics-to-todoist#42]
**Describe the bug**
Probably some requirements are not met in package file. 

When I try to run application, using command:
`ics-to-todoist.exe Downloads\e1889228824810268.ics`
or with config file:
`ics-to-todoist.exe Downloads\e1889228824810268.ics --cofig-path todoist.config`
I got:
`
λ ics-to-todoist.exe Downloads\e1889228824810268.ics
Traceback (most recent call last):
  File "c:\programs\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programs\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Programs\Python39\Scripts\ics-to-todoist.exe\__main__.py", line 4, in <module>
  File "c:\programs\python39\lib\site-packages\ics_to_todoist\__main__.py", line 2, in <module>
    import tomllib
ModuleNotFoundError: No module named 'tomllib'
`

**Desktop:**
 - OS: Windows 10 Home 64-bit

**Comment by gaborschulz** [comment]
> **Describe the bug** Probably some requirements are not met in package file.
> 
> When I try to run application, using command: `ics-to-todoist.exe Downloads\e1889228824810268.ics` or with config file: `ics-to-todoist.exe Downloads\e1889228824810268.ics --cofig-path todoist.config` I got: `λ ics-to-todoist.exe Downloads\e1889228824810268.ics Traceback (most recent call last): File "c:\programs\python39\lib\runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "c:\programs\python39\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "C:\Programs\Python39\Scripts\ics-to-todoist.exe\__main__.py", line 4, in <module> File "c:\programs\python39\lib\site-packages\ics_to_todoist\__main__.py", line 2, in <module> import tomllib ModuleNotFoundError: No module named 'tomllib'`
> 
> **Desktop:**
> 
> * OS: Windows 10 Home 64-bit

Hi,

thanks for raising the question. The problem is caused by Python 3.9 not having `tomllib` built in. However, if you try to run it in a Python 3.10+ environment it should work.
